### PR TITLE
Fix unused tests

### LINKED ISSUE #54: Excluded tests are broken
The test suite passes on Travis but will fail on local machines.  This is because only 3 out of 5 test files are run by Travis (`test_units_helpers.py, test_update_metadata.py, test_decompose_flow_vectors.py`).  Running `pytest` with excluded files (`test_split_merged_climos.py, test_create_climo_files.py`) break with a collection of similar errors:
```
tests/test_split_merged_climos.py:69: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dp/split_merged_climos.py:51: in split_merged_climos
    output_filepath = os.path.join(outdir, cf.cmor_filename)
/tmp/venv/lib/python3.6/site-packages/nchelpers/decorators.py:26: in wrapper
    res = func(*args, **kwargs)
/tmp/venv/lib/python3.6/site-packages/nchelpers/__init__.py:351: in __getattribute__
    value = super(CFDataset, self).__getattribute__(name)
/tmp/venv/lib/python3.6/site-packages/nchelpers/__init__.py:1568: in cmor_filename
    extension='.nc', **self._cmor_type_filename_components()
/tmp/venv/lib/python3.6/site-packages/nchelpers/__init__.py:1494: in _cmor_type_filename_components
    components.update(ensemble_member=self.ensemble_member)
/tmp/venv/lib/python3.6/site-packages/nchelpers/decorators.py:26: in wrapper
    res = func(*args, **kwargs)
/tmp/venv/lib/python3.6/site-packages/nchelpers/__init__.py:351: in __getattribute__
    value = super(CFDataset, self).__getattribute__(name)
/tmp/venv/lib/python3.6/site-packages/nchelpers/__init__.py:562: in ensemble_member
    components[component] = getattr(self.gcm, attr)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <nchelpers.CFDataset.AutoGcmPrefixedAttribute object at 0x7fb510b52748>, attr = 'realization'

    def __getattr__(self, attr):
        prefixed_attr = self._prefixed(attr)
        try:
            return getattr(self.dataset, prefixed_attr)
        except AttributeError:
            raise CFAttributeError(
                "Expected file to contain attribute '{}' but no such "
>               "attribute exists".format(self._prefixed(attr)))
E           nchelpers.exceptions.CFAttributeError: Expected file to contain attribute 'GCM__realization' but no such attribute exists
```
Generally, there is an attribute being accessed that does not exist named `[some prefix]__realization`.

One of threes things could be done:
1. Fix the broken tests
2. Remove the broken tests
3. Comment/Explain why the tests are broken/excluded

### PR DESCRIPTION
**Pull request by nikola-rados**
This fixes #54 by updating the metadata found in some of the test files.  Using the [update_metadata](https://github.com/pacificclimate/climate-explorer-data-prep/blob/master/scripts/update_metadata) script and the pcic metadata standard I was able to rename a number of globals in each of the files.

### YAML files
Since the metadata changes can't be easily viewed, I will provide the `.yaml` files that I used with `udpdate_metadata`.

#### For `tiny_hydromodel_gcm_climos.nc` and `tiny_hydromodel_gcm.nc`
```
global:
        downscaling__method: <-forcing_downscaling_method
        downscaling__method_id: <-forcing_downscaling_method_id
        downscaling__package_id: <-forcing_downscaling_package_id

        downscaling__GCM__experiment: <-forcing_driving_experiment
        downscaling__GCM__experiment_id: <-forcing_driving_experiment_id
        downscaling__GCM__initialization_method: <-forcing_driving_initialization_method
        downscaling__GCM__institute_id: <-forcing_driving_institute_id
        downscaling__GCM__institution: <-forcing_driving_institution
        downscaling__GCM__model_id: <-forcing_driving_model_id
        downscaling__GCM__physics_version: <-forcing_driving_physics_version
        downscaling__GCM__realization: <-forcing_driving_realization

        model_cal__contact: <-forcing_target_contact
        model_cal__dataset: <-forcing_target_dataset
        model_cal__dataset_id: <-forcing_target_dataset_id
        model_cal__institute_id: <-forcing_target_institute_id
        model_cal__institution: <-forcing_target_institution
        model_cal__references: <-forcing_target_references
        model_cal__version: <-forcing_target_version

        method_id: <-hydromodel_method_id
```

#### For `tiny_downscaled_pr.nc` and `tiny_downscaled_pr_packed.nc`
This was the only place where missing data was added as oppose to being renamed.
```
global:
        project_id: 'CMIP5'
```

#### For `tiny_downscaled_tasmax.nc`, `tiny_downscaled_tasmax_climos.nc`, `tiny_downscaled_pr.nc` and `tiny_downscaled_pr_packed.nc`
```
global:
  GCM__experiment: <-driving_experiment
  GCM__experiment_id: <-driving_experiment_id
  GCM__institution: <-driving_institution
  GCM__institute_id: <-driving_institute_id
  GCM__model_id: <-driving_model_id
  GCM__realization: <-driving_realization
  GCM__initialization_method: <-driving_initialization_method
  GCM__physics_version: <-driving_physics_version

  method: <-downscaling_method
  method_id: <-downscaling_method_id
  package_id: <-downscaling_package_id

  target__institution: <-target_institution
  target__institute_id: <-target_institute_id
  target__dataset: <-target_dataset
  target__dataset_id: <-target_dataset_id
  target__references: <-target_references
  target__version: <-target_version
  target__contact: <-target_contact
```
All the test files will now pass on **local machine**, however cdo and travis still refuse to get along and thus the same test files (`test_split_merged_climos.py`, `test_create_climo_files.py`) will be excluded from the travis tests.

### CODE REVIEW

**Comment by corviday** [comment]
After @rod-glover confirms that your hydromodel metadata update YAML is correct, please add it to data-prep-actions; it would be nice to have a consistent and well-documented process for doing this update. We'll probably have to do it again.

**Comment by nikola-rados** [comment]
Ya that sounds like a good idea @corviday!

**Comment by rod-glover** [comment]
Reviewing now.

**Comment by rod-glover** [comment]
Good work, @nikola-rados ! Metadata is gnarly, and I applaud you for figuring all this out.

I have a few questions/requests:

Note: (*) indicates something that is probably not required to work with `nchelpers `and/or pass tests, but is required in the PCIC metadata standard and is important enought to warrant having right in our test files.

1. What are the values of the attribute `product` for each of these test files? Or, rather, please verify that they meet the standard. (*)

1. For `tiny_hydromodel_gcm_climos.nc` and `tiny_hydromodel_gcm.nc`:
   1. Please ensure that `forcing_type` and `forcing_domain` are set correctly. (*)
   1. Otherwise, looks good.

1. For `tiny_downscaled_pr.nc` and `tiny_downscaled_pr_packed.nc`:
   1. Just to verify, the only thing that was done was to set `project_id`? No renames?

1. For `tiny_downscaled_tasmax.nc`, `tiny_downscaled_tasmax_climos.nc`, `tiny_downscaled_pr.nc` and `tiny_downscaled_pr_packed.nc`:
   1. All looks good.

**Comment by nikola-rados** [comment]
Thanks for the review @rod-glover!

1. All the files adhere to the standard.  For `tiny_downscaled_pr.nc`, `tiny_downscaled_pr_packed.nc`, `tiny_downscaled_tasmax.nc` and `tiny_downscaled_tasmax_climos.nc` `product: "downscaled output"`.  For `tiny_hydromodel_gcm_climos.nc` and `tiny_hydromodel_gcm.nc` `product: "hydrological model output"`

2. So here `tiny_hydromodel_gcm_climos.nc` and `tiny_hydromodel_gcm.nc` had `forcing_type: "downscaled gcm"`, but neither file had `forcing_domain`.  Looking at the standards for _hydrological models forced by downscaled GCM data_ `forcing_domain` is **not** mandatory.

3. `tiny_downscaled_tasmax.nc`, `tiny_downscaled_tasmax_climos.nc`, `tiny_downscaled_pr.nc` and `tiny_downscaled_pr_packed.nc` all had the same renames done.  However, **only** `tiny_downscaled_pr.nc` and `tiny_downscaled_pr_packed.nc` required `project_id` to be added.

4. :+1:

**Comment by rod-glover** [comment]
OK. LGTM!

**Pull request merged**
